# Generated by Django 4.2.5 on 2023-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(choices=[(1, 'ativo'), (2, 'inativo')], default=True)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=12)),
                ('user', models.CharField(choices=[(1, 'aluno'), (2, 'professor')], default='', max_length=20)),
            ],
        ),
    ]
