# Generated by Django 4.2.5 on 2023-09-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(choices=[(1, 'aluno'), (2, 'professor')], default='1', max_length=20),
        ),
    ]
