# Generated by Django 4.2.5 on 2023-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.PositiveIntegerField(choices=[(1, 'aluno'), (2, 'professor')], default='1', max_length=5),
        ),
    ]
